[package]
name = "stremio-derive"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "1.0.*"
quote = "1.0.*"
proc-macro2 = "1.0.*"
proc-macro-crate = "0.1.*"
proc_macro_roids = "0.7.*"
case = "1.0.*"
