name: Build

on: [push]

# Stops the running workflow of previous pushes
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: stable

jobs:
  build:
    name: Lint, test and build
    runs-on: ubuntu-latest

    steps:
    - name: Set default Rust version - ${{ env.RUST_VERSION }}
      run: rustup default ${{ env.RUST_VERSION }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint - rustfmt
      run: cargo fmt --all -- --check

    - name: Lint - clippy
      run: cargo clippy --all --no-deps -- -D warnings

    - name: Test
      run: cargo test

    - name: Build
      run: cargo build